# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: txn.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='txn.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\ttxn.proto\"\x19\n\tByteArray\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c\"\xd4\x01\n\x18ProtoTransactionCoreInfo\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\r\n\x05nonce\x18\x02 \x01(\x04\x12\x0e\n\x06toaddr\x18\x03 \x01(\x0c\x12 \n\x0csenderpubkey\x18\x04 \x01(\x0b\x32\n.ByteArray\x12\x1a\n\x06\x61mount\x18\x05 \x01(\x0b\x32\n.ByteArray\x12\x1c\n\x08gasprice\x18\x06 \x01(\x0b\x32\n.ByteArray\x12\x10\n\x08gaslimit\x18\x07 \x01(\x04\x12\x0c\n\x04\x63ode\x18\x08 \x01(\x0c\x12\x0c\n\x04\x64\x61ta\x18\t \x01(\x0c')
)




_BYTEARRAY = _descriptor.Descriptor(
  name='ByteArray',
  full_name='ByteArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ByteArray.data', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=38,
)


_PROTOTRANSACTIONCOREINFO = _descriptor.Descriptor(
  name='ProtoTransactionCoreInfo',
  full_name='ProtoTransactionCoreInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='ProtoTransactionCoreInfo.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='ProtoTransactionCoreInfo.nonce', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toaddr', full_name='ProtoTransactionCoreInfo.toaddr', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='senderpubkey', full_name='ProtoTransactionCoreInfo.senderpubkey', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='ProtoTransactionCoreInfo.amount', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gasprice', full_name='ProtoTransactionCoreInfo.gasprice', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gaslimit', full_name='ProtoTransactionCoreInfo.gaslimit', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='ProtoTransactionCoreInfo.code', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='ProtoTransactionCoreInfo.data', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=253,
)

_PROTOTRANSACTIONCOREINFO.fields_by_name['senderpubkey'].message_type = _BYTEARRAY
_PROTOTRANSACTIONCOREINFO.fields_by_name['amount'].message_type = _BYTEARRAY
_PROTOTRANSACTIONCOREINFO.fields_by_name['gasprice'].message_type = _BYTEARRAY
DESCRIPTOR.message_types_by_name['ByteArray'] = _BYTEARRAY
DESCRIPTOR.message_types_by_name['ProtoTransactionCoreInfo'] = _PROTOTRANSACTIONCOREINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ByteArray = _reflection.GeneratedProtocolMessageType('ByteArray', (_message.Message,), dict(
  DESCRIPTOR = _BYTEARRAY,
  __module__ = 'txn_pb2'
  # @@protoc_insertion_point(class_scope:ByteArray)
  ))
_sym_db.RegisterMessage(ByteArray)

ProtoTransactionCoreInfo = _reflection.GeneratedProtocolMessageType('ProtoTransactionCoreInfo', (_message.Message,), dict(
  DESCRIPTOR = _PROTOTRANSACTIONCOREINFO,
  __module__ = 'txn_pb2'
  # @@protoc_insertion_point(class_scope:ProtoTransactionCoreInfo)
  ))
_sym_db.RegisterMessage(ProtoTransactionCoreInfo)


# @@protoc_insertion_point(module_scope)
